# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straat', models.CharField(max_length=255)),
                ('huisnummer', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'adressen',
            },
        ),
        migrations.CreateModel(
            name='Gebruiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefoonnummer', models.CharField(max_length=255)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Adres')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('naam_nl', models.CharField(max_length=255, null=True)),
                ('naam_en', models.CharField(max_length=255, null=True)),
                ('naam_fr', models.CharField(max_length=255, null=True)),
                ('landcode', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'landen',
            },
        ),
        migrations.CreateModel(
            name='Woonplaats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10)),
                ('gemeente', models.CharField(max_length=255)),
                ('gemeente_nl', models.CharField(max_length=255, null=True)),
                ('gemeente_en', models.CharField(max_length=255, null=True)),
                ('gemeente_fr', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'woonplaatsen',
            },
        ),
        migrations.AddField(
            model_name='adres',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Land'),
        ),
        migrations.AddField(
            model_name='adres',
            name='woonplaats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Woonplaats'),
        ),
    ]
