# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straat', models.CharField(max_length=255)),
                ('huisnummer', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('gemeente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gebruiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('voornaam', models.CharField(max_length=255)),
                ('telefoonnummer', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('wachtwoord', models.CharField(max_length=255)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('landcode', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Permissie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('permissies', models.ManyToManyField(to='gebruikers.Permissie')),
            ],
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Rol'),
        ),
        migrations.AddField(
            model_name='adres',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Land'),
        ),
    ]
