# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikers', '0002_auto_20160421_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permissies',
        ),
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name_plural': 'Adressen'},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'verbose_name_plural': 'Landen'},
        ),
        migrations.DeleteModel(
            name='Permissie',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
