# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikers', '0003_auto_20160421_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebruiker',
            name='adres',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Adres'),
        ),
    ]
