# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikers', '0005_auto_20160422_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woonplaats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10)),
                ('gemeente', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Woonplaatsen',
            },
        ),
        migrations.RemoveField(
            model_name='adres',
            name='gemeente',
        ),
        migrations.RemoveField(
            model_name='adres',
            name='postcode',
        ),
        migrations.AddField(
            model_name='adres',
            name='woonplaats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Woonplaats'),
        ),
    ]
