# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikers', '0006_auto_20160521_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='woonplaats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Woonplaats'),
        ),
    ]
