# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikers', '0007_auto_20160521_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name_plural': 'adressen'},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'verbose_name_plural': 'landen'},
        ),
        migrations.AlterModelOptions(
            name='woonplaats',
            options={'verbose_name_plural': 'woonplaatsen'},
        ),
    ]
