# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikers', '0008_auto_20160606_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='naam_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='naam_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='naam_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='woonplaats',
            name='gemeente_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='woonplaats',
            name='gemeente_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='woonplaats',
            name='gemeente_nl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
