# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierDocBeschrijving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_naam', models.CharField(max_length=100)),
                ('dossier_naam_nl', models.CharField(max_length=100, null=True)),
                ('dossier_naam_en', models.CharField(max_length=100, null=True)),
                ('dossier_naam_fr', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dossier Document Beschrijvingen',
            },
        ),
        migrations.CreateModel(
            name='DossierDocLijn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestand', models.FileField(blank=True, null=True, upload_to=b'')),
                ('beschrijving', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.DossierDocBeschrijving')),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panden.Pand')),
            ],
            options={
                'verbose_name_plural': 'Dossier Document Lijnen',
            },
        ),
        migrations.CreateModel(
            name='DossierDocStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('status_nl', models.CharField(max_length=100, null=True)),
                ('status_en', models.CharField(max_length=100, null=True)),
                ('status_fr', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dossier Document Statussen',
            },
        ),
        migrations.CreateModel(
            name='Stavaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('status_nl', models.CharField(max_length=100, null=True)),
                ('status_en', models.CharField(max_length=100, null=True)),
                ('status_fr', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': "Stavaza's",
            },
        ),
        migrations.CreateModel(
            name='StavazaLijn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.date.today)),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panden.Pand')),
                ('stavaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.Stavaza')),
            ],
            options={
                'verbose_name_plural': 'Stavazalijnen',
            },
        ),
        migrations.AddField(
            model_name='dossierdoclijn',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.DossierDocStatus'),
        ),
        migrations.AlterUniqueTogether(
            name='dossierdoclijn',
            unique_together=set([('pand', 'beschrijving')]),
        ),
    ]
