# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={'verbose_name_plural': 'Dossiers'},
        ),
        migrations.AlterModelOptions(
            name='dossierdocbeschrijving',
            options={'verbose_name_plural': 'Dossier Document Beschrijvingen'},
        ),
        migrations.AlterModelOptions(
            name='dossierdoclijn',
            options={'verbose_name_plural': 'Dossier Document Lijnen'},
        ),
        migrations.AlterModelOptions(
            name='dossierdocstatus',
            options={'verbose_name_plural': 'Dossier Document Statussen'},
        ),
        migrations.AlterModelOptions(
            name='stavaza',
            options={'verbose_name_plural': "Stavaza's"},
        ),
        migrations.AlterModelOptions(
            name='stavazalijn',
            options={'verbose_name_plural': 'Stavazalijnen'},
        ),
        migrations.RenameField(
            model_name='dossier',
            old_name='pand_id',
            new_name='pand',
        ),
        migrations.RenameField(
            model_name='dossierdocbeschrijving',
            old_name='dossier_doc_lijn_id',
            new_name='dossier_doc_lijn',
        ),
        migrations.RenameField(
            model_name='dossierdoclijn',
            old_name='dossier_id',
            new_name='dossier',
        ),
        migrations.RenameField(
            model_name='dossierdocstatus',
            old_name='dossier_doc_lijn_id',
            new_name='dossier_doc_lijn',
        ),
        migrations.RenameField(
            model_name='stavaza',
            old_name='stavaza_lijn_id',
            new_name='stavaza_lijn',
        ),
        migrations.RenameField(
            model_name='stavazalijn',
            old_name='dossier_id',
            new_name='dossier',
        ),
    ]
