# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_auto_20160421_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierdocbeschrijving',
            name='dossier_doc_lijn',
        ),
        migrations.RemoveField(
            model_name='dossierdocstatus',
            name='dossier_doc_lijn',
        ),
        migrations.RemoveField(
            model_name='stavaza',
            name='stavaza_lijn',
        ),
        migrations.AddField(
            model_name='dossierdoclijn',
            name='beschrijving',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.DossierDocBeschrijving'),
        ),
        migrations.AddField(
            model_name='dossierdoclijn',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.DossierDocStatus'),
        ),
        migrations.AddField(
            model_name='stavazalijn',
            name='stavaza',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.Stavaza'),
        ),
    ]
