# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('talen', '0002_auto_20160421_1426'),
        ('dossiers', '0003_auto_20160422_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='actief',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dossierdocbeschrijving',
            name='kan_doc_bevatten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossierdocstatus',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='talen.Label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stavazalijn',
            name='datum',
            field=models.DateField(default=datetime.datetime(2016, 4, 26, 9, 51, 47, 188000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dossierdocbeschrijving',
            name='dossier_naam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talen.Label'),
        ),
    ]
