# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_auto_20160426_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavaza',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talen.Label'),
        ),
    ]
