# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_auto_20160426_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='pand',
        ),
    ]
