# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0011_remove_pand_dossier'),
        ('dossiers', '0006_remove_dossier_pand'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='pand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='panden.Pand'),
        ),
    ]
