# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0008_auto_20160504_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierdoclijn',
            name='bestand',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
