# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0009_auto_20160504_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavazalijn',
            name='datum',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
