# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0010_auto_20160504_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavazalijn',
            name='stavaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.Stavaza'),
        ),
    ]
