# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0016_pand_actief'),
        ('dossiers', '0011_auto_20160506_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='pand',
        ),
        migrations.RemoveField(
            model_name='dossierdoclijn',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='stavazalijn',
            name='dossier',
        ),
        migrations.AddField(
            model_name='dossierdoclijn',
            name='pand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panden.Pand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stavazalijn',
            name='pand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panden.Pand'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
    ]
