# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0013_auto_20160523_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierdoclijn',
            name='beschrijving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.DossierDocBeschrijving'),
        ),
        migrations.AlterField(
            model_name='dossierdoclijn',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.DossierDocStatus'),
        ),
    ]
