# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0014_auto_20160531_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dossierdoclijn',
            unique_together=set([('pand', 'beschrijving')]),
        ),
    ]
