# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0015_auto_20160531_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierdocbeschrijving',
            name='kan_doc_bevatten',
        ),
    ]
