# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0016_remove_dossierdocbeschrijving_kan_doc_bevatten'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdocbeschrijving',
            name='dossier_naam_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossierdocbeschrijving',
            name='dossier_naam_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossierdocbeschrijving',
            name='dossier_naam_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossierdocstatus',
            name='status_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossierdocstatus',
            name='status_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossierdocstatus',
            name='status_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stavaza',
            name='status_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stavaza',
            name='status_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stavaza',
            name='status_nl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
