# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ViaSofie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faq_item',
            new_name='FaqItem',
        ),
    ]
