# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViaSofie', '0003_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='actief',
            field=models.BooleanField(default=True),
        ),
    ]
