# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViaSofie', '0005_auto_20160606_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partner-img'),
        ),
    ]
