# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViaSofie', '0006_auto_20160606_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='prioriteit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
