# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViaSofie', '0008_partner_prioriteit'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='tekst_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='tekst_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='tekst_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='titel_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='titel_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='titel_nl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
