# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gebruikers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kenmerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benaming', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prijs', models.FloatField()),
                ('bouwjaar', models.DateField()),
                ('oppervlakte', models.FloatField()),
                ('algemene_beschrijving', models.TextField()),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Adres')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebruikers.Gebruiker')),
            ],
        ),
        migrations.CreateModel(
            name='PandImmoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_beschrijving', models.CharField(max_length=255)),
                ('site_link', models.CharField(max_length=255)),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panden.Pand')),
            ],
        ),
        migrations.CreateModel(
            name='PandKenmerkPerPand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal', models.PositiveSmallIntegerField()),
                ('kenmerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panden.Kenmerk')),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panden.Pand')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pand',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panden.Type'),
        ),
        migrations.AddField(
            model_name='foto',
            name='pand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panden.Pand'),
        ),
        migrations.AlterUniqueTogether(
            name='pandkenmerkperpand',
            unique_together=set([('pand', 'kenmerk')]),
        ),
    ]
