# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='kenmerken',
            field=models.ManyToManyField(through='panden.PandKenmerkPerPand', to='panden.Kenmerk'),
        ),
    ]
