# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0002_pand_kenmerken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name_plural': "Foto's"},
        ),
        migrations.AlterModelOptions(
            name='kenmerk',
            options={'verbose_name_plural': 'Kenmerken'},
        ),
        migrations.AlterModelOptions(
            name='pand',
            options={'verbose_name_plural': 'Panden'},
        ),
        migrations.AlterModelOptions(
            name='pandimmolink',
            options={'verbose_name_plural': 'Immolinks'},
        ),
        migrations.AlterModelOptions(
            name='pandkenmerkperpand',
            options={'verbose_name_plural': 'Kenmerken per pand'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'Types'},
        ),
    ]
