# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0003_auto_20160421_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='foto_link',
        ),
        migrations.AddField(
            model_name='foto',
            name='foto',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
