# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_remove_dossier_pand'),
        ('panden', '0005_auto_20160422_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='dossier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dossiers.Dossier'),
            preserve_default=False,
        ),
    ]
