# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0006_pand_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pand',
            name='dossier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.Dossier'),
        ),
    ]
