# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0007_auto_20160426_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to=b'')),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panden.Pand')),
            ],
            options={
                'verbose_name_plural': "Foto's voor carousel",
            },
        ),
    ]
