# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0008_carouselfoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselfoto',
            name='pand',
        ),
        migrations.AddField(
            model_name='carouselfoto',
            name='actief',
            field=models.BooleanField(default=True),
        ),
    ]
