# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0009_auto_20160429_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselfoto',
            name='foto',
            field=models.ImageField(upload_to=b''),
        ),
    ]
