# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0010_auto_20160429_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pand',
            name='dossier',
        ),
    ]
