# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0011_remove_pand_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='kenmerk',
            name='is_aantal',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
