# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0012_kenmerk_is_aantal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pand',
            name='bouwjaar',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
