# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0013_auto_20160506_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pandkenmerkperpand',
            options={'verbose_name': 'Pandkenmerk', 'verbose_name_plural': 'Pandkenmerken'},
        ),
        migrations.AlterField(
            model_name='pandimmolink',
            name='site_beschrijving',
            field=models.CharField(max_length=255, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='pandimmolink',
            name='site_link',
            field=models.CharField(max_length=255, verbose_name='link'),
        ),
    ]
