# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0014_auto_20160509_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselfoto',
            options={'verbose_name': 'foto voor slideshow', 'verbose_name_plural': 'Slideshow'},
        ),
    ]
