# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0015_auto_20160518_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='actief',
            field=models.BooleanField(default=True),
        ),
    ]
