# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0016_pand_actief'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
