# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0017_pand_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='KenmerkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='kenmerk',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panden.KenmerkType'),
        ),
    ]
