# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0018_auto_20160530_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=20)),
                ('waarde', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'optie',
                'verbose_name_plural': 'opties',
            },
        ),
    ]
