# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0019_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandimmolink',
            name='logo',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
