# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0021_auto_20160603_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandimmolink',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panden.ImmoSite'),
            preserve_default=False,
        ),
    ]
