# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0022_pandimmolink_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselfoto',
            options={'verbose_name': 'foto voor slideshow', 'verbose_name_plural': 'slideshow'},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name_plural': "foto's"},
        ),
        migrations.AlterModelOptions(
            name='kenmerk',
            options={'verbose_name_plural': 'kenmerken'},
        ),
        migrations.AlterModelOptions(
            name='pand',
            options={'verbose_name_plural': 'panden'},
        ),
        migrations.AlterModelOptions(
            name='pandimmolink',
            options={'verbose_name_plural': 'immolinks'},
        ),
        migrations.AlterModelOptions(
            name='pandkenmerkperpand',
            options={'verbose_name': 'pandkenmerk', 'verbose_name_plural': 'pandkenmerken'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'types'},
        ),
    ]
