# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0024_auto_20160609_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kenmerk',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panden.KenmerkType'),
        ),
    ]
