# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panden', '0026_auto_20160609_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='type_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='type_nl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
