# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Taalcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taalcode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TaalcodePerLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertaling', models.CharField(max_length=255)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talen.Label')),
                ('taalcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talen.Taalcode')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taalcodeperlabel',
            unique_together=set([('label', 'taalcode')]),
        ),
    ]
