# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name_plural': 'Labels'},
        ),
        migrations.AlterModelOptions(
            name='taalcode',
            options={'verbose_name_plural': 'Taalcodes'},
        ),
        migrations.AlterModelOptions(
            name='taalcodeperlabel',
            options={'verbose_name_plural': 'Vertalingen'},
        ),
    ]
